workflows:
  my-workflow:
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Run tests
        script: |
          export BROWSERSTACK_USERNAME=khalidshaikh_Cc8Pao
          export BROWSERSTACK_ACCESS_KEY=Nwmh7iXkfjAqcWDECMXx
          export BROWSERSTACK_APP_URL=bs://67a7dc8b5919f1ab1b5e6539a29de600ff450f1d
          npm run bstack-parallel
          
